<a href="https://colab.research.google.com/github/youssefjedidi/Aircraft_Noise_Predictor/blob/main/aircraft_noise_predictor_ML_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('aircraft_noise.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[['LAmax' 'A' 1500 'Piston']
 ['LAmax' 'A' 1600 'Piston']
 ['LAmax' 'A' 27 'Piston']
 ...
 ['SEL' 'D' 28000 'Jet']
 ['EPNL' 'D' 32000 'Jet']
 ['SEL' 'D' 32000 'Jet']]


## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [  1 , 0 ,3 ])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1.0 0.0 1500]
 [1.0 0.0 0.0 ... 1.0 0.0 1600]
 [1.0 0.0 0.0 ... 1.0 0.0 27]
 ...
 [0.0 1.0 0.0 ... 0.0 0.0 28000]
 [0.0 1.0 1.0 ... 0.0 0.0 32000]
 [0.0 1.0 0.0 ... 0.0 0.0 32000]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[63.48 59.5 ]
 [56.31 55.8 ]
 [71.04 86.5 ]
 ...
 [72.07 73.5 ]
 [71.65 65.6 ]
 [69.45 61.5 ]]


## Testing accuracy

In [ ]:
def mean_absolute_percentage_error(y_true, y_pred):
    return (np.mean(np.abs((y_true - y_pred) / y_true)) * 100)

mape = mean_absolute_percentage_error(y_test, y_pred)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
print(regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_pred)

# Print MSE
print(f" R squared  (r2): {r2:.2f}")

Mean Absolute Percentage Error (MAPE): 9.94%
[43.62]
 R squared  (r2): 0.55
