<a href="https://colab.research.google.com/github/youssefjedidi/Aircraft_Noise_Predictor/blob/main/aircraft_noise_predictor_ML_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Regression models

## Importing the libraries

In [463]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [464]:
dataset = pd.read_csv('aircraft_noise.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [465]:
print(y)

[ 26.7  27.7  28.5 ... 100.6 101.8 102.2]


## Encoding categorical data

In [466]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [  1 , 0 , 3 , 4 ])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [467]:
print(X)

[[1.0 0.0 0.0 ... 0.0 1.0 1500]
 [1.0 0.0 0.0 ... 0.0 1.0 1600]
 [1.0 0.0 0.0 ... 0.0 1.0 27]
 ...
 [0.0 1.0 0.0 ... 0.0 0.0 28000]
 [0.0 1.0 1.0 ... 0.0 0.0 32000]
 [0.0 1.0 0.0 ... 0.0 0.0 32000]]


## Splitting the dataset into the Training set and Test set

In [468]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

## Multiple Linear Regression


### Training the Multiple Linear Regression model on the Training set

In [469]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Predicting the Test set results

In [470]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[54.46 56.7 ]
 [70.88 68.4 ]
 [56.51 56.8 ]
 ...
 [71.66 65.1 ]
 [46.95 41.6 ]
 [47.32 48.  ]]


### Testing accuracy

In [471]:
def mean_absolute_percentage_error(y_true, y_pred):
    return (np.mean(np.abs((y_true - y_pred) / y_true)) * 100)

mape = mean_absolute_percentage_error(y_test, y_pred)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_pred)

# Print MSE
print(f" R squared  (r2): {r2:.2f}")

Mean Absolute Percentage Error (MAPE): 8.43%
 R squared  (r2): 0.62


## Polynomial Regression

### Training

In [472]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 3)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

### Predecting the Test set Results

In [473]:
y_poly = lin_reg_2.predict(poly_reg.fit_transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_poly.reshape(len(y_poly),1), y_test.reshape(len(y_test),1)),1))

[[52.11 56.7 ]
 [70.82 68.4 ]
 [61.18 56.8 ]
 ...
 [75.78 65.1 ]
 [45.47 41.6 ]
 [41.89 48.  ]]


### Testing accuracy

In [474]:

mape = mean_absolute_percentage_error(y_test, y_poly)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(lin_reg_2.predict(poly_reg.fit_transform([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]])))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2_poly = r2_score(y_test, y_poly)

# Print MSE
print(f" R squared  (r2): {r2_poly:.2f}")

Mean Absolute Percentage Error (MAPE): 7.68%
 R squared  (r2): 0.67


## Support Vector Regression (SVR)

### Feature Scaling

In [475]:
from sklearn.preprocessing import StandardScaler

# Reshape input data to 2D array
X_reshaped = X[:, 3].reshape(-1, 1)  # Reshape only the fourth column
X_test_reshaped = X_test[:, 3].reshape(-1, 1)

# Initialize StandardScaler for the fourth column
sc_X = StandardScaler()

# Fit and transform the fourth column
X_scaled = X.copy()  # Create a copy of X to keep other columns unchanged
X_scaled[:, 3] = sc_X.fit_transform(X_reshaped).flatten()  # Scale and update the fourth column

X_test_scaled = X_test.copy()
X_test_scaled[:, 3] = sc_X.fit_transform(X_test_reshaped).flatten()

# Initialize StandardScaler for the target variable
sc_y = StandardScaler()
y_scaled = sc_y.fit_transform(y.reshape(-1, 1))  # Fit and transform the target variable
y_test_scaled = sc_y.fit_transform(y_test.reshape(-1, 1))

# Now X_scaled and y_scaled are scaled versions of X and y using StandardScaler
print("Scaled X:")
print(X_scaled)
print("\nScaled y:")
print(y_scaled)

Scaled X:
[[1.0 0.0 0.0 ... 0.0 1.0 1500]
 [1.0 0.0 0.0 ... 0.0 1.0 1600]
 [1.0 0.0 0.0 ... 0.0 1.0 27]
 ...
 [0.0 1.0 0.0 ... 0.0 0.0 28000]
 [0.0 1.0 1.0 ... 0.0 0.0 32000]
 [0.0 1.0 0.0 ... 0.0 0.0 32000]]

Scaled y:
[[-3.06]
 [-2.97]
 [-2.9 ]
 ...
 [ 3.36]
 [ 3.47]
 [ 3.5 ]]


### Training the SVR model

In [476]:
from sklearn.svm import SVR
sv_regressor = SVR(kernel = 'rbf')
sv_regressor.fit(X_scaled, y_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

### Predicting

In [477]:
# Perform predictions using the SVR model on the scaled test features
y_svr_scaled = sv_regressor.predict(X_test_scaled)

# Inverse transform the scaled predictions to get them back to the original scale
y_svr = sc_y.inverse_transform(y_svr_scaled.reshape(-1, 1))

np.set_printoptions(precision=2)
print(np.concatenate((y_svr.reshape(len(y_svr),1), y_test.reshape(len(y_test),1)),1))

[[55.66 56.7 ]
 [63.2  68.4 ]
 [68.63 56.8 ]
 ...
 [67.57 65.1 ]
 [54.25 41.6 ]
 [55.92 48.  ]]


### Testing accuracy

In [478]:

mape = mean_absolute_percentage_error(y_test, y_svr)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2_poly = r2_score(y_test, y_svr)

# Print MSE
print(f" R squared  (r2): {r2_poly:.2f}")

Mean Absolute Percentage Error (MAPE): 17.70%
 R squared  (r2): 0.30


## Decision Tree

### Training the Decision Tree model on the Training set

In [542]:
from sklearn.tree import DecisionTreeRegressor
tree_regressor = DecisionTreeRegressor(random_state=42)
tree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

###Predicting

In [543]:
y_tree = tree_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_tree.reshape(len(y_tree),1), y_test.reshape(len(y_test),1)),1))

[[58.8  56.7 ]
 [65.6  68.4 ]
 [60.2  56.8 ]
 ...
 [84.29 65.1 ]
 [43.4  41.6 ]
 [54.4  48.  ]]


### Testing accuracy

In [545]:
mape = mean_absolute_percentage_error(y_test, y_tree)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(tree_regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_tree)

# Print MSE
print(f" R squared  (r2): {r2:.4f}")

Mean Absolute Percentage Error (MAPE): 7.58%
 R squared  (r2): 0.6426


## Random Forest

### Training the Random Forest model on the Training set

In [537]:
from sklearn.ensemble import RandomForestRegressor
forest_regressor = RandomForestRegressor(n_estimators = 100)
forest_regressor.fit(X_train, y_train)

RandomForestRegressor()

### Predicting

In [538]:
y_forest = forest_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_forest.reshape(len(y_forest),1), y_test.reshape(len(y_test),1)),1))

[[57.36 56.7 ]
 [65.66 68.4 ]
 [59.   56.8 ]
 ...
 [84.3  65.1 ]
 [46.42 41.6 ]
 [50.69 48.  ]]


### Testing accuracy

In [539]:
mape = mean_absolute_percentage_error(y_test, y_forest)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(tree_regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_forest)

# Print MSE
print(f" R squared  (r2): {r2:.4f}")

Mean Absolute Percentage Error (MAPE): 7.18%
 R squared  (r2): 0.6889
