<a href="https://colab.research.google.com/github/youssefjedidi/Aircraft_Noise_Predictor/blob/main/aircraft_noise_predictor_ML_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Regression models

## Importing the libraries

In [430]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [431]:
dataset = pd.read_csv('aircraft_noise.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [432]:
print(X)

[['LAmax' 'A' 1500 ... 1 1695 2325]
 ['LAmax' 'A' 1600 ... 1 1695 2325]
 ['PNLTM' 'A' 1500 ... 1 1695 2325]
 ...
 ['EPNL' 'D' 80000 ... 4 6752 1254430]
 ['SEL' 'D' 80000 ... 4 6837 1254430]
 ['EPNL' 'D' 80000 ... 4 6837 1254430]]


## Encoding categorical data

In [433]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [  1 , 0 , 3 ,4  ])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [434]:
print(X)

[[1.0 0.0 0.0 ... 1 1695 2325]
 [1.0 0.0 0.0 ... 1 1695 2325]
 [1.0 0.0 0.0 ... 1 1695 2325]
 ...
 [0.0 1.0 1.0 ... 4 6752 1254430]
 [0.0 1.0 0.0 ... 4 6837 1254430]
 [0.0 1.0 1.0 ... 4 6837 1254430]]


## Splitting the dataset into the Training set and Test set

In [435]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

## Multiple Linear Regression


### Training the Multiple Linear Regression model on the Training set

In [436]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Predicting the Test set results

In [437]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[52.65 49.1 ]
 [71.42 69.8 ]
 [68.44 61.  ]
 ...
 [67.17 62.9 ]
 [61.12 65.2 ]
 [50.41 45.2 ]]


### Testing accuracy

In [438]:
def mean_absolute_percentage_error(y_true, y_pred):
    return (np.mean(np.abs((y_true - y_pred) / y_true)) * 100)

mape = mean_absolute_percentage_error(y_test, y_pred)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_pred)

# Calculate adjusted R squared
n = len(y_test)  # Number of samples
p = X.shape[1]   # Number of predictors (features) in your model
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Print R-squared and adjusted R-squared
print(f"R squared (r2): {r2:.4f}")
print(f"Adjusted R squared (adj_r2): {adj_r2:.4f}")

Mean Absolute Percentage Error (MAPE): 8.36%
R squared (r2): 0.6604
Adjusted R squared (adj_r2): 0.6504


## Polynomial Regression

### Training

In [439]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

### Predecting the Test set Results

In [440]:
y_poly = lin_reg_2.predict(poly_reg.fit_transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_poly.reshape(len(y_poly),1), y_test.reshape(len(y_test),1)),1))

[[50.5  49.1 ]
 [72.2  69.8 ]
 [61.8  61.  ]
 ...
 [69.3  62.9 ]
 [60.68 65.2 ]
 [51.17 45.2 ]]


### Testing accuracy

In [441]:

mape = mean_absolute_percentage_error(y_test, y_poly)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(lin_reg_2.predict(poly_reg.fit_transform([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]])))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2_poly = r2_score(y_test, y_poly)

# Calculate adjusted R squared
n = len(y_test)  # Number of samples
p = X.shape[1]   # Number of predictors (features) in your model
adj_r2 = 1 - (1 - r2_poly) * (n - 1) / (n - p - 1)

# Print R-squared and adjusted R-squared
print(f"R squared (r2): {r2_poly:.4f}")
print(f"Adjusted R squared (adj_r2): {adj_r2:.4f}")

Mean Absolute Percentage Error (MAPE): 7.07%
R squared (r2): 0.7528
Adjusted R squared (adj_r2): 0.7455


## Support Vector Regression (SVR)

### Feature Scaling

In [442]:
from sklearn.preprocessing import StandardScaler

# Reshape input data to 2D array
X_reshaped = X[:, 3].reshape(-1, 1)  # Reshape only the fourth column
X_test_reshaped = X_test[:, 3].reshape(-1, 1)

# Initialize StandardScaler for the fourth column
#sc_X = StandardScaler()

# Fit and transform the fourth column
X_scaled = X.copy()  # Create a copy of X to keep other columns unchanged
for i in range(-4,0):
  sc_X = StandardScaler()
  X_scaled[:, i] = sc_X.fit_transform(X_reshaped).flatten()  # Scale and update the fourth column


X_test_scaled = X_test.copy()
for i in range(-4,0):
  sc_X = StandardScaler()
  X_test_scaled[:, i] = sc_X.fit_transform(X_test_reshaped).flatten()


# Initialize StandardScaler for the target variable
sc_y = StandardScaler()
y_scaled = sc_y.fit_transform(y.reshape(-1, 1))  # Fit and transform the target variable
y_test_scaled = sc_y.fit_transform(y_test.reshape(-1, 1))

# Now X_scaled and y_scaled are scaled versions of X and y using StandardScaler
print("Scaled X:")
print(X_scaled)
print("\nScaled y:")
print(y_scaled)

Scaled X:
[[1.0 0.0 0.0 ... 1.7320508075688774 1.7320508075688774
  1.7320508075688774]
 [1.0 0.0 0.0 ... 1.7320508075688774 1.7320508075688774
  1.7320508075688774]
 [1.0 0.0 0.0 ... -0.5773502691896258 -0.5773502691896258
  -0.5773502691896258]
 ...
 [0.0 1.0 1.0 ... -0.5773502691896258 -0.5773502691896258
  -0.5773502691896258]
 [0.0 1.0 0.0 ... -0.5773502691896258 -0.5773502691896258
  -0.5773502691896258]
 [0.0 1.0 1.0 ... -0.5773502691896258 -0.5773502691896258
  -0.5773502691896258]]

Scaled y:
[[-3.06]
 [-2.97]
 [-2.82]
 ...
 [ 1.74]
 [ 2.05]
 [ 2.23]]


### Training the SVR model

In [443]:
from sklearn.svm import SVR
sv_regressor = SVR(kernel = 'rbf')
sv_regressor.fit(X_scaled, y_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

### Predicting

In [444]:
# Perform predictions using the SVR model on the scaled test features
y_svr_scaled = sv_regressor.predict(X_test_scaled)

# Inverse transform the scaled predictions to get them back to the original scale
y_svr = sc_y.inverse_transform(y_svr_scaled.reshape(-1, 1))

np.set_printoptions(precision=2)
print(np.concatenate((y_svr.reshape(len(y_svr),1), y_test.reshape(len(y_test),1)),1))

[[55.73 49.1 ]
 [65.44 69.8 ]
 [71.1  61.  ]
 ...
 [61.14 62.9 ]
 [61.39 65.2 ]
 [48.27 45.2 ]]


### Testing accuracy

In [445]:

mape = mean_absolute_percentage_error(y_test, y_svr)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2_svr = r2_score(y_test, y_svr)

# Calculate adjusted R squared
n = len(y_test)  # Number of samples
p = X.shape[1]   # Number of predictors (features) in your model
adj_r2 = 1 - (1 - r2_svr) * (n - 1) / (n - p - 1)

# Print R-squared and adjusted R-squared
print(f"R squared (r2): {r2_svr:.4f}")
print(f"Adjusted R squared (adj_r2): {adj_r2:.4f}")

Mean Absolute Percentage Error (MAPE): 19.68%
R squared (r2): 0.6199
Adjusted R squared (adj_r2): 0.6086


## Decision Tree

> Add blockquote



### Training the Decision Tree model on the Training set

In [446]:
from sklearn.tree import DecisionTreeRegressor
tree_regressor = DecisionTreeRegressor(random_state=42)
tree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

###Predicting

In [447]:
y_tree = tree_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_tree.reshape(len(y_tree),1), y_test.reshape(len(y_test),1)),1))

[[49.1 49.1]
 [65.  69.8]
 [61.  61. ]
 ...
 [67.6 62.9]
 [71.5 65.2]
 [45.2 45.2]]


### Testing accuracy

In [448]:
mape = mean_absolute_percentage_error(y_test, y_tree)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(tree_regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_tree)
# Calculate adjusted R squared
n = len(y_test)  # Number of samples
p = X.shape[1]   # Number of predictors (features) in your model
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Print R-squared and adjusted R-squared
print(f"R squared (r2): {r2:.4f}")
print(f"Adjusted R squared (adj_r2): {adj_r2:.4f}")

Mean Absolute Percentage Error (MAPE): 4.06%
R squared (r2): 0.8897
Adjusted R squared (adj_r2): 0.8864


## Random Forest

### Training the Random Forest model on the Training set

In [458]:
from sklearn.ensemble import RandomForestRegressor
forest_regressor = RandomForestRegressor(n_estimators = 350)
forest_regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=350)

### Predicting

In [459]:
y_forest = forest_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_forest.reshape(len(y_forest),1), y_test.reshape(len(y_test),1)),1))

[[47.01 49.1 ]
 [66.33 69.8 ]
 [60.32 61.  ]
 ...
 [64.63 62.9 ]
 [67.37 65.2 ]
 [48.15 45.2 ]]


### Testing accuracy

In [464]:
mape = mean_absolute_percentage_error(y_test, y_forest)

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
#print(tree_regressor.predict([[1, 0, 0, 1 ,0 ,0 , 0,0 ,1 , 300 , 2 , 2624 , 13000 ]]))

from sklearn.metrics import r2_score

# Assuming y_test contains the actual target values and y_pred contains the predicted values
# Calculate R squared
r2 = r2_score(y_test, y_forest)
# Calculate adjusted R squared
n = len(y_test)  # Number of samples
p = X.shape[1]   # Number of predictors (features) in your model
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Print R-squared and adjusted R-squared
print(f"R squared (r2): {r2:.4f}")
print(f"Adjusted R squared (adj_r2): {adj_r2:.4f}")

Mean Absolute Percentage Error (MAPE): 3.64%
R squared (r2): 0.9300
Adjusted R squared (adj_r2): 0.9279
